### ISSUE TITLE
snmpindex error

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.Aruba.Instant#4]
Caught this gem over the weekend:
```python
Traceback (most recent call last):
  File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 669, in processClient
    datamaps = plugin.process(device, results, self.log)
  File "/opt/zenoss/ZenPacks/ZenPacks.daviswr.Aruba.Instant-0.7.0-py2.7.egg/ZenPacks/daviswr/Aruba/Instant/modeler/plugins/daviswr/snmp/ArubaInstant.py", line 395, in process
    for radio_index in ap_radios[ap['snmpindex']]:
KeyError: 'snmpindex'
```
Device from which the error originated is `ArubaOS (MODEL: 315), Version 8.3.0.8-8.3.0.8`

**Comment by daviswr** [comment]
Hm.. Not quite sure what configuration would lead to that scenario. I might email later asking for some specific SNMP walks if that's alright. A debug run of `zenmodeler` against the AP in question limited to `--collect=daviswr.snmp.ArubaInstant` would be helpful in the mean time, though. Email's fine for that so details aren't out here on GH.

Is the AP in question a cluster member that's being monitored individually, or a truly stand-alone AP (Maintenance > Convert > Stand Alone)? tbh, I haven't done much with the latter case.

Are there other APs monitored in similar configs?

All that said, I've tried to add some basic safety checks for this in 5911f537d2ed62c1727f023a97db7067b00e0ead . Let me know what that does?

**Comment by sempervictus** [comment]
The safeties look solid. I'll get the new zenpack into the stack sometime this week.
The AP is part of a small cluster - 3 total, and its been monitored for quite a while. There wasnt any activity around that event either, seems to have "come out of the blue."
